In [1]:
import numpy as np


In [2]:
# 1 Generate marks between 0 and 100 for 50 students
marks = np.random.randint(0, 101, 50)

print(marks)

[26 42 24 36 43  1 64 89 56 19 37 11  6 25 26 28 50 39  4 42 51 33 98 76
 98 70 93 28 32 51 58 88 74 28 23 88 55 19 87  5 53 12 60 11 74 60 76 83
 21 97]


In [3]:
#42. Calculate Total, Average, Highest, Lowest
# Total Marks
print("Total Marks:", np.sum(marks))

# Average Marks
print("Average Marks:", np.mean(marks))

# Highest Marks
print("Highest Marks:", np.max(marks))

# Lowest Marks
print("Lowest Marks:", np.min(marks))

Total Marks: 2370
Average Marks: 47.4
Highest Marks: 98
Lowest Marks: 1


In [4]:
# 43. Count Above 75, Below 35, Between 35–75
# Count students above 75
print("Above 75:", np.sum(marks > 75))

# Count students below 35
print("Below 35:", np.sum(marks < 35))

# Count students between 35 and 75
print("Between 35 and 75:", np.sum((marks >= 35) & (marks <= 75)))

Above 75: 11
Below 35: 20
Between 35 and 75: 19


In [5]:
# 44.Assign Grades
grades = np.where(marks >= 75, "A",
         np.where(marks >= 60, "B",
         np.where(marks >= 35, "C", "F")))

print(grades)

['F' 'C' 'F' 'C' 'C' 'F' 'B' 'A' 'C' 'F' 'C' 'F' 'F' 'F' 'F' 'F' 'C' 'C'
 'F' 'C' 'C' 'F' 'A' 'A' 'A' 'B' 'A' 'F' 'F' 'C' 'C' 'A' 'B' 'F' 'F' 'A'
 'C' 'F' 'A' 'F' 'C' 'F' 'B' 'F' 'B' 'B' 'A' 'A' 'F' 'A']


In [6]:
#45 Display Top 5 Marks
top5 = np.sort(marks)[-5:]

print("Top 5 Marks:", top5)

Top 5 Marks: [89 93 97 98 98]


In [7]:
# 46. Display Bottom 5 Marks
bottom5 = np.sort(marks)[:5]

print("Bottom 5 Marks:", bottom5)

Bottom 5 Marks: [ 1  4  5  6 11]


In [8]:
#47. Find Median and Standard Deviation
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))

Median: 42.5
Standard Deviation: 28.37886537548674


In [9]:
#48. Create 5-Subject Marks Matrix and Calculate Totals
# Marks of 10 students in 5 subjects
subject_marks = np.random.randint(35, 101, (10, 5))

print("Marks Matrix:")
print(subject_marks)

# Total marks of each student
totals = np.sum(subject_marks, axis=1)

print("Student Totals:")
print(totals)

Marks Matrix:
[[ 74  50  65  74  35]
 [ 52  43  90  69  89]
 [ 61  38  72  83  98]
 [ 75  75  42  95  63]
 [ 83  41  90  79  43]
 [ 46  91  44  96  96]
 [ 37  81  44  67  41]
 [ 99  97  50  95  83]
 [ 76  65 100  43  64]
 [ 75  71  56  46  39]]
Student Totals:
[298 343 352 350 336 373 270 424 348 287]


In [10]:
#49. Find Topper in Each Subject
# Highest marks in each subject
topper_subject = np.max(subject_marks, axis=0)

print("Topper Marks in Each Subject:")
print(topper_subject)

Topper Marks in Each Subject:
[ 99  97 100  96  98]


In [11]:
#50. Generate Report Card with Total, Average, Percentage and Grade
# Average and Percentage
average = np.mean(subject_marks, axis=1)
percentage = average

# Grade Calculation
grades = np.where(percentage >= 75, "A",
         np.where(percentage >= 60, "B",
         np.where(percentage >= 35, "C", "F")))

# Report Card
for i in range(len(subject_marks)):
    print("\nStudent", i + 1)
    print("Total Marks:", totals[i])
    print("Average:", round(average[i], 2))
    print("Percentage:", round(percentage[i], 2))
    print("Grade:", grades[i])


Student 1
Total Marks: 298
Average: 59.6
Percentage: 59.6
Grade: C

Student 2
Total Marks: 343
Average: 68.6
Percentage: 68.6
Grade: B

Student 3
Total Marks: 352
Average: 70.4
Percentage: 70.4
Grade: B

Student 4
Total Marks: 350
Average: 70.0
Percentage: 70.0
Grade: B

Student 5
Total Marks: 336
Average: 67.2
Percentage: 67.2
Grade: B

Student 6
Total Marks: 373
Average: 74.6
Percentage: 74.6
Grade: B

Student 7
Total Marks: 270
Average: 54.0
Percentage: 54.0
Grade: C

Student 8
Total Marks: 424
Average: 84.8
Percentage: 84.8
Grade: A

Student 9
Total Marks: 348
Average: 69.6
Percentage: 69.6
Grade: B

Student 10
Total Marks: 287
Average: 57.4
Percentage: 57.4
Grade: C
