In [1]:
import numpy as np

In [2]:
# 1. NumPy version
print("1.", np.__version__)

1. 2.5.1


In [3]:
# Create a Python list
my_list = [10, 20, 30, 40, 50]


In [4]:

#2. Convert list into NumPy array
arr = np.array(my_list)

# Display array
print(arr)

[10 20 30 40 50]


In [5]:
#3. Create a 3x3 array filled with zeros
zeros_array = np.zeros((3, 3))
print("Zeros Array:")
print(zeros_array)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Create a 3x3 array filled with ones
ones_array = np.ones((3, 3))
print("\nOnes Array:")
print(ones_array)


Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# Create a 3x3 array filled with value 7
full_array = np.full((3, 3), 7)
print("\nFull Array:")
print(full_array)


Full Array:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [8]:
#4. Create a 4x4 identity matrix
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
#5. Generate numbers from 1 to 10 using arrange().
arr1 = np.arange(1, 11)
print("Using arange():")
print(arr1)

Using arange():
[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# Generate 5 equally spaced values between 0 and 1 using linspace().
arr2 = np.linspace(0, 1, 5)
print("\nUsing linspace():")
print(arr2)


Using linspace():
[0.   0.25 0.5  0.75 1.  ]


In [11]:
#6. Create matrix from 1 to 9
matrix = np.arange(1, 10).reshape(3, 3)

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# 7.check Shape of matrix
print("Shape:", matrix.shape)

# size
print("Size:", matrix.size)

# dimensions
print("Dimensions:", matrix.ndim)

# Data type
print("Data Type:", matrix.dtype)

Shape: (3, 3)
Size: 9
Dimensions: 2
Data Type: int64


In [13]:
#8. Convert integer array to float array
float_arr = arr.astype(float)

# Display float array
print(float_arr)

[10. 20. 30. 40. 50.]


In [14]:
#9. Generate 10 random integers
random_arr = np.random.randint(1, 101, 10)

print(random_arr)

[64 13 25 74 90  8 98 65 42 35]


In [15]:
#11. Access First element
print("First:", random_arr[0])

# Middle element
print("Middle:", random_arr[len(random_arr)//2])

# Last element
print("Last:", random_arr[-1])

First: 64
Middle: 8
Last: 35


In [16]:
#12. Extract first 5 elements
print(random_arr[:5])

[64 13 25 74 90]


In [17]:
#13. Reverse the random_arr created earlier
reversed_arr = random_arr[::-1]

print(reversed_arr)

[35 42 65 98  8 90 74 25 13 64]


In [18]:
#14. Create 1D array with 12 elements
arr_1d = np.arange(1, 13)



In [19]:

# Reshape into 3 rows and 4 columns
reshaped_arr = arr_1d.reshape(3, 4)

print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
# 15.Flatten the reshaped array from Question 14
flat_arr = reshaped_arr.flatten()

print(flat_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
#16. Transpose the matrix created in Question 14
transpose_matrix = reshaped_arr.T

print(transpose_matrix)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [22]:
#17. Find sum of each row
row_sum = reshaped_arr.sum(axis=1)

#  sum of each column
col_sum = reshaped_arr.sum(axis=0)

# Display results
print("Row-wise Sum:", row_sum)
print("Column-wise Sum:", col_sum)

Row-wise Sum: [10 26 42]
Column-wise Sum: [15 18 21 24]


In [23]:
#18 Concatenate Arrays Horizontally and Vertically
# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [24]:
# Horizontal concatenation
horizontal = np.hstack((arr1, arr2))

# Vertical concatenation
vertical = np.vstack((arr1, arr2))

# Display results
print("Horizontal Concatenation:")
print(horizontal)

print("\nVertical Concatenation:")
print(vertical)

Horizontal Concatenation:
[[1 2 5 6]
 [3 4 7 8]]

Vertical Concatenation:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
# 19 Split the flattened array into 3 equal parts
split_arr = np.split(flat_arr, 3)

print(split_arr)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


In [26]:
# 20 Create a copy of reshaped array
swap_matrix = reshaped_arr.copy()

# Swap first and last rows
swap_matrix[[0, -1]] = swap_matrix[[-1, 0]]

print(swap_matrix)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [27]:
import numpy as np
#21 Element-wise Arithmetic
# Create two arrays
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])


In [28]:
# Addition
print("Addition:", arr1 + arr2)

# Subtraction
print("Subtraction:", arr1 - arr2)

# Multiplication
print("Multiplication:", arr1 * arr2)

# Division
print("Division:", arr1 / arr2)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [29]:
#22. Square of elements
print("Square:", arr1 ** 2)

# Square root of elements
print("Square Root:", np.sqrt(arr1))

# Cube of elements
print("Cube:", arr1 ** 3)

Square: [100 400 900]
Square Root: [3.16227766 4.47213595 5.47722558]
Cube: [ 1000  8000 27000]


In [30]:
# Using random_arr created earlier

#23 find Minimum value
print("Minimum:", np.min(random_arr))

# Maximum value
print("Maximum:", np.max(random_arr))

# Average value
print("Average:", np.mean(random_arr))

Minimum: 8
Maximum: 98
Average: 51.4


In [31]:
#24 Find sum ,of all elements in random_arr

total = np.sum(random_arr)

# Display sum
print("Sum:", total)

Sum: 514


In [32]:
#25 Find cumulative sum of random_arr
cumulative_sum = np.cumsum(random_arr)

# Display result
print(cumulative_sum)

[ 64  77 102 176 266 274 372 437 479 514]


In [33]:
# 26 Using arr1 and arr2 from Question 21
#Dot product
dot_product = np.dot(arr1, arr2)

print("Dot Product:", dot_product)

Dot Product: 140


In [34]:
#27 Create two matrices for matrix multiplication.
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])


In [35]:
# Matrix multiplication
result = np.matmul(matrix1, matrix2)

print(result)

[[19 22]
 [43 50]]


In [36]:
# 28 Find determinant  of matrix1

det = np.linalg.det(matrix1)

print("Determinant:", det)

Determinant: -2.0000000000000004


In [37]:
#29 Find inverse of matrix1

inverse_matrix = np.linalg.inv(matrix1)

# Display result
print(inverse_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [38]:
# Using random_arr created earlier

#30  Standard Deviation
print("Standard Deviation:", np.std(random_arr))

# Variance
print("Variance:", np.var(random_arr))

Standard Deviation: 29.880428377116683
Variance: 892.8399999999999


In [39]:
# 31 Display even numbers from random_arr

even_numbers = random_arr[random_arr % 2 == 0]

print(even_numbers)

[64 74 90  8 98 42]


In [40]:
# 32 Display odd numbers from random_arr

odd_numbers = random_arr[random_arr % 2 != 0]

print(odd_numbers)

[13 25 65 35]


In [41]:
# 33 Display elements greater than 50

greater_than_50 = random_arr[random_arr > 50]

print(greater_than_50)

[64 74 90 98 65]


In [42]:
# 34 Create an array with negative values
arr = np.array([-5, 10, -2, 15, -8])

# Replace negative values with 0
arr[arr < 0] = 0

print(arr)

[ 0 10  0 15  0]


In [43]:
# Find average of random_arr
average = np.mean(random_arr)

#35 Count values above average
count = np.sum(random_arr > average)

print("Average:", average)
print("Count Above Average:", count)

Average: 51.4
Count Above Average: 5


In [44]:
# Create array with duplicate values
dup_arr = np.array([10, 20, 30, 20, 40, 50, 10, 60])

#36 Find duplicate values
unique, counts = np.unique(dup_arr, return_counts=True)

duplicates = unique[counts > 1]

print("Duplicate Values:", duplicates)

Duplicate Values: [10 20]


In [45]:
#37 Remove duplicate values from dup_arr

unique_values = np.unique(dup_arr)

print(unique_values)

[10 20 30 40 50 60]


In [46]:
#38 Sort random_arr in ascending order
ascending = np.sort(random_arr)

# Sort random_arr in descending order
descending = np.sort(random_arr)[::-1]

print("Ascending Order:")
print(ascending)

print("\nDescending Order:")
print(descending)

Ascending Order:
[ 8 13 25 35 42 64 65 74 90 98]

Descending Order:
[98 90 74 65 64 42 35 25 13  8]


In [47]:
# 39 Find indices of elements greater than 75

indices = np.where(random_arr > 75)

print(indices)

(array([4, 6]),)


In [48]:
# Create a copy of random_arr
modified_arr = random_arr.copy()

#40 Replace even numbers with -1
modified_arr[modified_arr % 2 == 0] = -1

print(modified_arr)

[-1 13 25 -1 -1 -1 -1 65 -1 35]


In [49]:
# 41 Generate marks between 0 and 100 for 50 students

marks = np.random.randint(0, 101, 50)

print(marks)

[ 99  10  72  49  64  98  93  45  45  82   4  96  79  41  58  23  79  91
  21  56  84   0  15  30   7  68  49  12  80  72  83  85 100  78  76  85
  25  88   5  62  93  31  95  34  67  74  77  27  16  84]


In [50]:
# Calculate statistics for marks array
#42 calculate total,average, highest,lowest.
print("Total Marks:", np.sum(marks))
print("Average Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))

Total Marks: 2907
Average Marks: 58.14
Highest Marks: 100
Lowest Marks: 0


In [51]:
#Count Above 75, Below 35, Between 35–75
# Count students scoring above 75
above_75 = np.sum(marks > 75)

# Count students scoring below 35
below_35 = np.sum(marks < 35)

# Count students scoring between 35 and 75
between_35_75 = np.sum((marks >= 35) & (marks <= 75))

print("Above 75:", above_75)
print("Below 35:", below_35)
print("Between 35 and 75:", between_35_75)

Above 75: 21
Below 35: 15
Between 35 and 75: 14


In [52]:
# 44 Assign grades based on marks

grades = np.where(marks >= 75, "A",
         np.where(marks >= 60, "B",
         np.where(marks >= 35, "C", "F")))

print(grades)

['A' 'F' 'B' 'C' 'B' 'A' 'A' 'C' 'C' 'A' 'F' 'A' 'A' 'C' 'C' 'F' 'A' 'A'
 'F' 'C' 'A' 'F' 'F' 'F' 'F' 'B' 'C' 'F' 'A' 'B' 'A' 'A' 'A' 'A' 'A' 'A'
 'F' 'A' 'F' 'B' 'A' 'F' 'A' 'F' 'B' 'B' 'A' 'F' 'F' 'A']


In [53]:
# 45 display top 5 marks

top_5 = np.sort(marks)[-5:]

print(top_5)

[ 95  96  98  99 100]


In [54]:
#46 Display bottom 5 marks

bottom_5 = np.sort(marks)[:5]

print(bottom_5)

[ 0  4  5  7 10]


In [55]:
#47 Find median

print("Median:", np.median(marks))

#  standard deviation

print("Standard Deviation:", np.std(marks))

Median: 67.5
Standard Deviation: 30.6228738037435


In [56]:
# 48 Create 5-Subject Marks Matrix and Calculate Totals
#  Generate marks for 10 students in 5 subjects

subject_marks = np.random.randint(35, 101, (10, 5))

# Calculate total marks of each student

totals = np.sum(subject_marks, axis=1)

print("Marks Matrix:")
print(subject_marks)

print("\nTotal Marks:")
print(totals)

Marks Matrix:
[[ 73  55  87  90  83]
 [ 45  71  59  35  44]
 [ 94  79  45 100  54]
 [ 83  64  69  93  37]
 [ 66  99  86  77  89]
 [ 79  77  87  38  46]
 [ 70  79  49  35  67]
 [ 79  46  55  52  71]
 [ 86  95  93  91  51]
 [ 61  60  83  86  38]]

Total Marks:
[388 254 372 346 417 327 300 303 416 328]


In [57]:
# 49 Find Topper in Each Subject

subject_toppers = np.max(subject_marks, axis=0)

print(subject_toppers)

[ 94  99  93 100  89]


In [58]:
# 50 Generate Report Card with Total, Average, Percentage and Grade
# Calculate average and percentage

average = np.mean(subject_marks, axis=1)
percentage = average

# Assign grades

grades = np.where(percentage >= 75, "A",
         np.where(percentage >= 60, "B",
         np.where(percentage >= 35, "C", "F")))

# Display report card

for i in range(len(subject_marks)):
    print("Student", i + 1)
    print("Total:", totals[i])
    print("Average:", round(average[i], 2))
    print("Percentage:", round(percentage[i], 2))
    print("Grade:", grades[i])
    print("-" * 20)

Student 1
Total: 388
Average: 77.6
Percentage: 77.6
Grade: A
--------------------
Student 2
Total: 254
Average: 50.8
Percentage: 50.8
Grade: C
--------------------
Student 3
Total: 372
Average: 74.4
Percentage: 74.4
Grade: B
--------------------
Student 4
Total: 346
Average: 69.2
Percentage: 69.2
Grade: B
--------------------
Student 5
Total: 417
Average: 83.4
Percentage: 83.4
Grade: A
--------------------
Student 6
Total: 327
Average: 65.4
Percentage: 65.4
Grade: B
--------------------
Student 7
Total: 300
Average: 60.0
Percentage: 60.0
Grade: B
--------------------
Student 8
Total: 303
Average: 60.6
Percentage: 60.6
Grade: B
--------------------
Student 9
Total: 416
Average: 83.2
Percentage: 83.2
Grade: A
--------------------
Student 10
Total: 328
Average: 65.6
Percentage: 65.6
Grade: B
--------------------
